apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: 172.16.16.17:5001/eureka:v1
        env:
        - name: AUTHOR
          value: eureka
        ports:
        - containerPort: 7000