apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: 171.16.16.17:5001/config:v1
        env:
        - name: AUTHOR
          value: config-server
        ports:
        - containerPort: 12000